### ISSUE TITLE
Load jar with ammonite is too slow

### ISSUE THREAD

**Issue by dazebug** [alexarchambault/jupyter-scala#129]
I used to use `classpath.addPath` but it doesn't work anymore.

I figured out that I can load jars with ammonite
```scala
import ammonite._, ammonite.ops._
val jars = ls! root/'target/'pack/'lib |? (_.ext == "jar")
jars.map(interp.load.cp(_))
```

but this is far slower than `classpath.addPath`. Does anybody know how to make this faster?

**Comment by mallman** [comment]
@dazebug This is a major issue for me as well. As a step in the right direction, I contributed a commit to Ammonite which adds an overload to `load.cp` which takes multiple paths instead of just one:

https://github.com/lihaoyi/Ammonite/commit/08728680827083e0d7b1323ba3f544419fa45f7d

However, this hasn't been incorporated into an Ammonite release yet. When that happens, @alexarchambault will need to rebase Ammonium to bring that patch in. I suppose in theory he could just rebase off of the upstream master. @alexarchambault, is that a viable option?

Cheers.

**Comment by mallman** [comment]
As of jupyter-scala 0.4.0 `load.cp` can take a `Seq[Path]` of jar files. I've tried it and it is *much* faster than adding them one-by-one. I suggest you upgrade and use the new method.

Cheers.

**Comment by dazebug** [comment]
Yeah it feels like is fast enough! Thank you for good news! @mallman
