### ISSUE TITLE
Value classes are not working

### ISSUE THREAD

**Issue by mtekp** [alexarchambault/jupyter-scala#88]
This is really a very awesome tool. And a great job, for providing scala kernal for jupyter notebook. I was creating a tutorial on scala types for a presentation and found value class not working. It works in Ammonite REPL though.

Not sure, but I think notebook works within a User instance and that's the reason for error. Any possible workaround?

```scala 
class ValueClass(val i:Int) extends AnyVal
 ```

results in 
Main.scala:23: value class may not be a member of another class
              class ValueClass(val i:Int) extends AnyVal

**Comment by mtekp** [comment]
Do we need clusterid and subsysid is required in TABLE metadata_column if glassbeam keyspace?

Also i see  val SUBSYSID = "subsysid" defined in 
```scala 
object com.glassbeam.Columns
``` 
need to clarify if both are different or same.

**Comment by alexarchambault** [comment]
That originates from the kernel wrapping the user code in a class (for Java serialization, thus spark, to be fine), instead of an object like the standard scala REPL.

There's a workaround for that though: adding `import special.wrap.obj` in the same cell as the value class definition makes the kernel wrap the user code of this cell in an object. The following:
```scala
import special.wrap.obj
class ValueClass(val i:Int) extends AnyVal
```
works fine.

**Comment by mtekp** [comment]
Thanks a lot. Works like a charm. Since I feel it cannot be supported directly. I am closing this issue.
